version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./server
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "5001:5000"

  frontend:
    build: ./client
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data:
